version: '2'
services:
  arma-3:
    image: "hasable/a3-server"
    container_name: "arma-3-server"
    ports:
      - "2302:2302/udp" 
      - "2303:2303/udp" 
      - "2304:2304/udp"
      - "2305:2305/udp"
      - "2306:2306/udp"